Ss/sample example
AdityaKBhadragond14/ApraPipes pull request #2
Opened 2024-05-20 09:50 UTC by SatwikSShanbhag

**IMPORTANT: All PRs must be linked to an issue (except for extremely trivial and straightforward changes).**

Fixes #[Issue]

**Description**

Precise description of the changes in this pull request

**Alternative(s) considered**

Have you considered any alternatives? And if so, why have you chosen the approach in this PR?

**Type**

Type Choose one: (Bug fix | Feature | Documentation | Testing | Other)

**Screenshots (if applicable)**

**Checklist**

- [x] I have read the [Contribution Guidelines](https://github.com/Apra-Labs/ApraPipes/wiki/Contribution-Guidelines)
- [x] I have written Unit Tests
- [x] I have discussed my proposed solution with code owners in the linked issue(s) and we have agreed upon the general approach

2024-06-13 09:20 UTC, mraduldubey requested changes
reviewed thumbnail sample - go throught the comments and make similar changes in other samples. This is good work apart from the comments I have made.

2024-06-13 09:20 UTC, mraduldubey commented on base/CMakeLists.txt
> +target_include_directories ( aprapipessampleut PRIVATE
remove the libs which are not required in any of the samples 
Also, the readme of the samples should clearly mention the dependent libraries

2024-06-13 09:20 UTC, mraduldubey commented on samples/create_thumbnail_from_mp4_video/CMakeLists.txt
> +SET(CORE_FILES
name it SAMPLE_FILES not CORE_FILES

2024-06-13 09:20 UTC, mraduldubey commented on samples/create_thumbnail_from_mp4_video/CMakeLists.txt
> +  ${JETSON_MULTIMEDIA_LIB_INCLUDE}
only add required dependencies and document in readme

2024-06-13 09:20 UTC, mraduldubey commented on samples/create_thumbnail_from_mp4_video/CMakeLists.txt
> +target_link_libraries(
only add required dependencies and document in readme

2024-06-13 09:20 UTC, mraduldubey commented on samples/create_thumbnail_from_mp4_video/GenerateThumbnailsPipeline.cpp
> +  mImagePin = mp4Reader->getAllOutputPinsByType(frameType);
add comment: // for selective pin connection in setNext

2024-06-13 09:20 UTC, mraduldubey commented on samples/create_thumbnail_from_mp4_video/GenerateThumbnailsPipeline.cpp
> +GenerateThumbnailsPipeline::GenerateThumbnailsPipeline()
replace "pipeline" with "thumnailSamplePipeline"

2024-06-13 09:20 UTC, mraduldubey commented on samples/create_thumbnail_from_mp4_video/GenerateThumbnailsPipeline.cpp
> +  valve = boost::shared_ptr<ValveModule>(new ValveModule(ValveModuleProps(0)));
add comment about what is 0 in the props

2024-06-13 09:20 UTC, mraduldubey commented on samples/create_thumbnail_from_mp4_video/GenerateThumbnailsPipeline.cpp
> +  auto mp4ReaderProps =
put one line comment for all modules - what does it do in the pipeline / why is it required

2024-06-13 09:20 UTC, mraduldubey commented on samples/create_thumbnail_from_mp4_video/GenerateThumbnailsPipeline.cpp
> +  pipeLine.init();
should return false if init() fails

2024-06-13 09:20 UTC, mraduldubey commented on samples/create_thumbnail_from_mp4_video/GenerateThumbnailsPipeline.cpp
> +bool GenerateThumbnailsPipeline::startPipeLine() {
format using vscode ctrl +k, f

2024-06-13 09:20 UTC, mraduldubey commented on samples/create_thumbnail_from_mp4_video/GenerateThumbnailsPipeline.h
> +    bool setUpPipeLine(const std::string &videoPath,const std::string &outFolderPath);
good job here having strings const

2024-06-13 09:20 UTC, mraduldubey commented on samples/create_thumbnail_from_mp4_video/GenerateThumbnailsPipeline.h
> +    PipeLine pipeLine;
rename these variables to have this format: mValve, mMp4Reader, mPipeline and so on. m stands for class member variable

2024-06-13 09:20 UTC, mraduldubey commented on samples/create_thumbnail_from_mp4_video/pipelineMain.cpp
> +#include "GenerateThumbnailsPipeline.h"
format using ctrl +k, f

2024-06-13 09:20 UTC, mraduldubey commented on samples/create_thumbnail_from_mp4_video/pipelineMain.cpp
> +  GenerateThumbnailsPipeline pipelineInstance;
call it thumbnailPipeline instead of pipelineINstance

2024-06-13 09:20 UTC, mraduldubey commented on samples/create_thumbnail_from_mp4_video/pipelineMain.cpp
> +  }
print a statement regarding sucess : Saved GeneratedThumbnail in <folder>

2024-06-13 09:20 UTC, mraduldubey commented on samples/create_thumbnail_from_mp4_video/test_generate_thumbnail_from_mp4_video.cpp
> +  std::string videoPath = "C:/APRA/fork/ApraPipes/data/Mp4_videos/h264_video_metadata/20230514/0011/1686723796848.mp4";
dont use absolute paths, use relative paths

2024-06-13 09:20 UTC, mraduldubey commented on samples/create_thumbnail_from_mp4_video/test_generate_thumbnail_from_mp4_video.cpp
> +  generateThumbnailPipeline->startPipeLine();
do a boost assert of this

2024-06-13 09:20 UTC, mraduldubey commented on samples/create_thumbnail_from_mp4_video/test_generate_thumbnail_from_mp4_video.cpp
> +  generateThumbnailPipeline->setUpPipeLine(videoPath, outFolderPath);
do a boost asser of this

2024-06-13 09:20 UTC, mraduldubey commented on samples/create_thumbnail_from_mp4_video/test_generate_thumbnail_from_mp4_video.cpp
> +      "C:/APRA/fork/ApraPipes/samples/create_thumbnail_from_mp4_video/data/generated_thumbnail/thumbnail_0000.jpg", pReadDataTest,
dont use absolute paths

2024-06-18 06:16 UTC, SatwikSShanbhag commented on samples/create_thumbnail_from_mp4_video/GenerateThumbnailsPipeline.h
> +    bool setUpPipeLine(const std::string &videoPath,const std::string &outFolderPath);
Thankyou

2024-06-24 13:48 UTC, mraduldubey requested changes
why are files related to timelapse delteted. change the cerr to cout, rest is ok

2024-06-24 13:48 UTC, mraduldubey commented on samples/create_thumbnail_from_mp4_video/pipelineMain.cpp
> +    std::cerr << "Saved Generated Thumbnail in <" << outFolderPath << ">";
this should not be a cerr

2024-07-04 09:29 UTC, merged